paryatak/urls.py
from django.conf.urls import url
from. import views

app_name='paryatak'

urlpatterns = [
    url(
        r'seat17/$',
        views.seat17,
        name='book-seat17'
    ),
    url(
        r'home/$',
        views.home,
        name='book-home'
    ),
    url(
        r'home/about/',
        views.about,
        name='book-about'
    ),
    url(
        r'home/login/',
        views.login,
        name='book-login'
    ),
    url(
        r'home/contact/',
        views.contact,
        name='book-contact'
    ),
    url(
        r'searchnew/$',
        views.BusListView.as_view(),
        name='search'    
    ),
    url(
        r'searchtickets/$',
        views.TicketListView.as_view(),
        name='search_tickets'
    ),
    url(
        r'searchnew/(?P<pk>\d+)/detail/$',
        views.bus_detail,
        name='bus_detail'
    ),
    url(
        r'searchnew/(?P<pk>\d+)/detail/(?P<sa>\d+)/$',
        views.SeatBookView.as_view(),
        name='samrat'
    ),
    url(
        r'searchtickets/(?P<pa>\d+)/$',
        views.cancelho.as_view(),
        name='samrat2'

    )
]  

users/urls.py
from django.conf.urls import include, url
from .views import *

urlpatterns=[
	url(r'bus/create$', BusCreate.as_view(), name='bus_create'),
	
]

paryatak/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone	
from users.models import *



class Bus(models.Model):
    no_of_seat = (
        (17, '17'),
        (25, '25'),
        (29, '29')
    )
    type_vehicle = (
        ('MICRO', 'MICRO'),
        ('BUS', 'BUS'),
        ('DEALUX', 'DEALUX')
    )
    capacity = models.IntegerField(
        choices=no_of_seat
    )
    bus_no = models.CharField(
        max_length=15
    )
    price = models.DecimalField(
        decimal_places=5,
        max_digits=10,
    )
    vehical_type = models.CharField(
        max_length=100,
        choices=type_vehicle
    )

    def __str__(self):
        return self.bus_no


class Seat(models.Model):
    bus = models.ForeignKey(
        Bus,
        on_delete=models.CASCADE,
        related_name="seats"
    )
    name = models.CharField(
        max_length=50
    )

    def __str__(self):
        return self.name


class BusTravel(models.Model):
    dest_from = (
        ('CHITWAN', 'CHITWAN'),
        ('KATHMANDU', 'KATHMANDU'),
        ('POKHARA', 'POKHARA'),
        ('JHAPA', 'JHAPA'),
    )
    dest_to = (
        ('CHITWAN', 'CHITWAN'),
        ('KATHMANDU', 'KATHMANDU'),
        ('POKHARA', 'POKHARA'),
        ('JHAPA', 'JHAPA'),
    )
    bus = models.ForeignKey(Bus,
        on_delete=models.CASCADE
    )
    destination_from = models.CharField(
        max_length=100,
        choices=dest_from
    )
    destination_to = models.CharField(
        max_length=100,
        choices=dest_to
    )
    departure_time = models.DateTimeField(auto_now=False)

    def __str__(self):
        return self.bus.bus_no


class BusTravelSeat(models.Model):
    bus_travel = models.ForeignKey(
        BusTravel,
        on_delete=models.CASCADE,
        related_name='bustravelseats'
    )
    seat = models.ForeignKey(
        Seat,
        on_delete=models.CASCADE
    )
    is_available = models.BooleanField(default=True)
    booked_time = models.DateTimeField(auto_now=True)
    customer = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        null=True  
    )

paryatak/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import *
from django.shortcuts import render
from .filters import BusFilter
from django.views.generic import TemplateView, DetailView, View
from django.db.models import Q
from django.core.mail import EmailMultiAlternatives
def home(request):
    print('inside home view')
    return render(request, 'paryatak/home.html')


def about(request):
    print('inside about view')
    return render(request, 'paryatak/about.html')

def login(request):
    print('inside about view')
    return render(request, 'paryatak/login.html')

def contact(request):
    print('inside about view')
    return render(request, 'paryatak/contact.html')


# def search(request):
#   bus_list = BusTravel.objects.all()
#   bus_filter = BusFilter(request.GET, queryset=bus_list)
#   return render(request, 'paryatak/search.html',{'filter': bus_filter})


def seat17(request):
    print('inside about view')
    return render(request, 'paryatak/seats.html')

class BusListView(TemplateView):
    template_name = 'paryatak/search.html'
    context_object_name = 'buses'

    def get(self, request, *args, **kwargs):
        departure_time = request.GET.get('departure_time', '')
        Destination_from = request.GET.get('Destination_from', '')
        Destination_to = request.GET.get('Destination_to', '')
        q = {
            'departure_time': departure_time,
            'Destination_from': Destination_from,
            'Destination_to': Destination_to
        };
        print('printing q >>', q);
        if (q != None and q['departure_time'] != '' and q['Destination_from'] != '' and q['Destination_to'] != ''):
            print('In if statement')
            buses = BusTravel.objects.filter(Q(
                destination_from__icontains=q['Destination_from']
            ) & (Q(
                destination_to__icontains=q['Destination_to'])
            )&Q(
            departure_time__icontains=q['departure_time']
            ))
        else:
            print('In else statement >>>>>');
            buses = BusTravel.objects.all()


        return render(request,self.template_name, {'buses':buses})

class BusDetailView(DetailView):
    model = BusTravel
    template_name = 'paryatak/bus_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        bus_travel_seats = BusTravelSeat.objects.filter(bus_travel=self)

        # context['seats']=bustravelseat_id
        return context


def bus_detail(request, pk):
    bus_travel = BusTravel.objects.get(id=pk)
    bus_travel_seats = BusTravelSeat.objects.filter(bus_travel=bus_travel).order_by('id')
    bus_name = bus_travel.bus.bus_no
    print (len(bus_name))
    bus_travel_seats_data = []
    for bus_travel_seat in bus_travel_seats:
        bus_travel_seat_data = {}
        bus_travel_seat_data['id'] = bus_travel_seat.id
        full_name = bus_travel_seat.seat.name
        slice_data = slice(len(bus_name)+1, len(full_name))
        name = full_name[slice_data]
        bus_travel_seat_data['name'] = name
        bus_travel_seat_data['is_available'] = bus_travel_seat.is_available
        bus_travel_seats_data.append(bus_travel_seat_data)
    print (bus_travel_seats_data)
    return render(request, 'paryatak/bus_detail.html', {
        'bus_travel': bus_travel,
        'bus_travel_seats': bus_travel_seats_data
    })

class SeatBookView(View):
    def get(self,request,*args,**kwargs):
        seat_id = self.kwargs.get('sa')
        bustravel_id = self.kwargs.get('pk')
        user = request.user
        customer_profile = Profile.objects.get(
            user=user
        )
        obj = BusTravelSeat.objects.get(id=seat_id)
        obj.is_available='False'
        obj.customer= customer_profile
        obj.save()
        bus_name = obj.bus_travel.bus
        seat_name = obj.seat.name
        subject,from_email,to = 'Parytak:Booking confirmed',settings.EMAIL_HOST_USER, user.email
        text_content='Hello, {}. your seat {} in bus {} for {} is booked. If you have any enquiries, contact us.'.format(user.username,obj.seat,obj.bus_travel,obj.booked_time)
        msg = EmailMultiAlternatives(subject,text_content,from_email,[to])
        msg.send()
        return redirect ('paryatak:bus_detail', pk=bustravel_id)


class TicketListView(TemplateView):
    template_name = 'paryatak/searchtickets.html'
    model = BusTravelSeat

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        print(self.request.user.profile,'\n\n\n\n')
        context['tickets']=BusTravelSeat.objects.filter(customer=self.request.user.profile)
        return context


class cancelho(View):
    def get(self,request,*args,**kwargs):
        seat_id = self.kwargs.get('pa')
        user = request.user
        obj = BusTravelSeat.objects.get(id=seat_id)
        obj.is_available='True'
        obj.customer= None
        obj.save()
        bus_name = obj.bus_travel.bus
        seat_name = obj.seat.name
        subject,from_email,to = 'Parytak:Booking cancelled',settings.EMAIL_HOST_USER, user.email
        text_content='Hello, {}. your seat {} in bus {} for {} is been cancelled. If you have any enquiries, contact us.'.format(user.username,obj.seat,obj.bus_travel,obj.booked_time)
        msg = EmailMultiAlternatives(subject,text_content,from_email,[to])
        msg.send()
        return redirect ('paryatak:search')

paryatak/templates/paryatak/about.html
{% extends "paryatak/base.html"%}

{% block content %}

{# 
<h2> KEC </h2>
<h2>BCT-B</h2>
<h2> Paryatak - A complete guide</h2>
</div>
<div class="ppp">
<p>Tourism is travel for pleasure or business; also the theory and practice of touring, the business of attracting, accommodating, and entertaining tourists, and the business of operating tours.[2] Tourism may be international, or within the traveller's country. The World Tourism Organization defines tourism more generally, in terms which go "beyond the common perception of tourism as being limited to holiday activity only", as people "traveling to and staying in places outside their usual environment for not more than one consecutive year for leisure and not less than 24 hours, business and other purposes".[3]</p>
<p>Tourism is travel for pleasure or business; also the theory and practice of touring, the business of attracting, accommodating, and entertaining tourists, and the business of operating tours.[2] Tourism may be international, or within the traveller's country. The World Tourism Organization defines tourism more generally, in terms which go "beyond the common perception of tourism as being limited to holiday activity only", as people "traveling to and staying in places outside their usual environment for not more than one consecutive year for leisure and not less than 24 hours, business and other purposes".[3]</p>
</div>
</article> #}
<div class="container">
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 font-weight-normal">Punny headline</h1>
    <p class="lead font-weight-normal color-blue">And an even wittier subheading to boot. Jumpstart your marketing efforts with this example based on Apple’s marketing pages.</p>
    <a class="btn btn-outline-secondary" href="#">Coming soon</a>
  </div>
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
</div>
</div>
<footer>

{% endblock content %}

paryatak/templates/paryatak/base.html
{% load static %}
<!DOCTYPE html>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}}">
	{{ message }}
</div>
{% endfor%}
{% endif %}

<html lang="en">
<head>
<meta charset="UTF-8">
<title>Paryatak - A Travel Guide </title>
 <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}"> 
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">  
<link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'bus_details.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">
<script src="JS/script.js"></script>
</head>
<body class="bg-light">
<header>
	<div class="container">
		<div class="row1">
	<figure class="col-xs-12 col-sm-3 col-md-3 logo-block">
        <a href="index.html"><h3>Prayatak:A Travelling Guide</h3> </a>
	</figure>
	<div class="col-xs-12 col-sm-9 col-md-9 header-right">
	<div class="top-menu">
		<ul>
			{% if user.is_authenticated %}
					<li><a href="/home"><i class="fa fa-home"></i>home </a></li>
		        	<li><a href="/home/about/"><i class="fa fa-users"></i>about us </a></li>
		        	<li><a href="/profile"><i class="fa fa-users"></i>profile</a></li>
		           	<li><a href="/home/contact"><i class="fa fa-flask"></i>contact us </a></li>
		        	<li><a href="../users/templates/users/logout"><i class="fa fa-home"></i>logout {{user.username}}</a></li>	
			{% else %}
			<li><a href="/home"><i class="fa fa-home"></i>home </a></li>
        	<li><a href="/home/about/"><i class="fa fa-users"></i>about us </a></li>
            <li><a href="{% url 'login' %}"><i class="fa fa-home"></i>Sign in </a></li>
        	<li><a href="/home/contact"><i class="fa fa-flask"></i>contact us </a></li>
        	{% endif %}
     	</ul>
	</div><!--top-menu-->
	<div class="company-info">
		<ul>
			<li><span class="phone"></span>
                    <div class="infos-right">
					<p>24/7 Support</p>
					<label>+977 9808799274</label>
                    </div>
			</li>
            
			<li><span class="email"></span>
			<div class="infos-right">
			<p>Email</p>
			<label><a href="mailto:shrestha.siddhartha06@outlook.com"> shrestha.siddhartha06@outlook.com</a></label>
			</div>
			</li>
			
            <li>
			<span class="trip"></span>
			<div class="infos-right">
			<p>Recommended By</p>
			<a href="review.html">
			<label>trip review</label>
			</a>
	</div>
			</li>
			<div class="clearfix"></div>
		</ul>
             </div><!--company-info-->
			</div><!--header-right-->

</div>
	</div>
</header>
    <nav class="nav nav-tabs">
<!--<div class="btn-group" role="group" aria-label="Basic example">        -->
<a class="nav-item" href="{% url 'discover' %}">Places to Visits</a> &nbsp; &nbsp; &nbsp;
<a class="nav-item" href="things_to_do.html"> Things to do</a> &nbsp; &nbsp; &nbsp;
<a class="nav-item" href="{% url 'discover' %}">Trekking sites</a> &nbsp; &nbsp; &nbsp;    
<a class="nav-item" href="whats_on.html">What's New?</a> &nbsp; &nbsp; &nbsp;    
<a class="nav-item" href="login.html">Sign in</a>&nbsp; &nbsp; &nbsp;
<a class="nav-item" href="maps.html">Maps</a> &nbsp; &nbsp; &nbsp;   
<a class="nav-item" href="privacy.html">Setting</a> &nbsp; &nbsp; &nbsp;   
<a class="nav-item" href="\">Office Location</a> &nbsp; &nbsp; &nbsp;
        
    </nav>    
<div class="aside">
<div class="aside_heading1">Trekking in Nepal</div>
<div class="text">  


<ul><strong>
<li>
<a href="/discover/1">anna</a>
</li>
</strong>
</ul>

<ul>
<strong>
<li>
<a href="poonhill_trek.html"> Poon Hill Trek</a>
</li>

</strong>
</ul>
<ul>
<strong>
<li>
<a href=""> Rara Lake Trek</a>
</li>
</strong>
</ul>
<ul>
<strong>
<li>
<a href="{% url 'discover' %}"> Mores...</a>
</li>

</strong>
</ul>        
</div>
<div class="aside_heading1">Places to visit</div>
<div class="text">  
<ul><strong>
<li>
<a href="/discover/4/">Lumbini:A birthplace of Gautam buddha</a>
</li>
</strong>
</ul>
<ul>
<strong>
<li>
<a href="/discover/5/"> Solukhumbhu District</a>
</li>

</strong>
</ul>
<ul>
<strong>
<li>
<a href="/discover/5/">Mustang </a>
</li>
</strong>
</ul>
<ul>
<strong>
<li>
<a href="{% url 'discover' %}"> Mores...</a>
</li>

</strong>
</ul>        
</div>    
<div class="aside_heading1">Other services</div>
<div class="text">  
<ul><strong>
<li>
<a href="ticket_booking.html">Bus ticket booking</a>
</li>
</strong>
</ul>
<ul>
<strong>
<li>
<a href="Vechile_rental.html"> Renting Vechicles </a>
</li>
</strong>
</ul>
<ul>
<strong>
<li>
<a href="maps.html"> Maps</a>
</li>
</strong>
</ul>

</div>
<div class="aside_heading3"><a href="contact.html">Testimonials</a></div>    
</div>
	<div class='main_content'>
    	{% block content %}{% endblock %}
    </div>
<footer>
	<div class="mainFooter">
		<div class="randomWidget">
			<h3 >Plan your Trip</h3>
			<a href="login.html" class="btn btn-outline-secondary">Search</a>
		</div>
		<h3 class="text-center footerHeading"> Quick Links.</h3>
		<div class="widget">
			<p><a href="login.html"><strong>Sign In</strong></a></p>
			<p><a href="register.html"><strong>Register</strong></a></p>
			<p><a href="contact.html"><strong>Contact Us</strong></a></p>
			<p><a href="review.html"><strong>Review</strong></a></p>
		</div>
		<div class="widget">    
			<p><a href="places_to_visit.html"><strong>Places to Visit</strong></a></p>
			<p><a href="things_to_do.html"><strong>Thing to do</strong></a></p>
			<p><a href="whats_on.html"><strong>What's On Nepal</strong></a></p>
			<p><a href="trekking_sites.html"><strong>Trekking Sites</strong></a></p>
		</div>
		<div class="widget">
			<p><a href="vechile_rental.html"><strong>Rent a Vehicle</strong></a></p>
			<p><a href="login.html"><strong>Ticket Booking</strong></a></p>
			<p><a href="packages.html"><strong> Packages</strong></a></p>    
			<p><a href="maps.html"><strong>Maps</strong></a></p>
		</div>

		<div class="widget">
			<p><a href="office_map.html"><strong> Office Location Map</strong></a></p>
			<p><a href=""><strong>FAQs</strong></a></p>
			<p><a href="privacy.html"><strong>Privacy and Cookies</strong></a></p>
			<p><a href="terms.html"><strong>Terms & Conditions</strong></a></p>
		</div>
	</div> 
	<div id="fot"> 
		&copy; 2076 Prayatak: Travelling guide &nbsp; Designed by Sid,Sag.T,Sag.K and Sam.
	</div>
</footer>
</body>
</html>

paryatak/templates/paryatak/bus_detail.html
{% extends "paryatak/base.html"%}
{% load static %}
{% block content %}
<h2>{{bus_travel.bus.bus_no}} details</h2>
<table>
	<tr>
		<td>Bus Number: </td>
		<td>{{bus_travel.bus.bus_no}}</td>
	</tr>
	<tr>
		<td>Price: </td>
		<td>{{bus_travel.bus.price}}</td>
	</tr>
	<tr>
		<td>Capacity: </td>
		<td>{{bus_travel.bus.capacity}}{{bus_travel.bus_travels.all}}</td>
	</tr>
</table>
	<div class="details_body">
	{% for i in bus_travel_seats %}
		{% if i.is_available %}
			
			<a class="seat seat_available" id = 'seat' href="{% url 'paryatak:samrat' bus_travel.id i.id %}">{{i.name}}</a>
			

		{% else %}
			<div class="seat seat_booked" >{{i.name}}</div>
		{%  endif %}
	{% endfor %}
	</div>

<script
			  src="https://code.jquery.com/jquery-3.4.1.js"
			  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
			  crossorigin="anonymous">
			  	
</script>
<script type="text/javascript">
	

		 $('#seat').click(function(){
			alert('Success! Your seat has been booked. Please check your email for more information');
				 		 
		});

	
</script>
{% endblock content %}

paryatak/templates/paryatak/contact.html
{% extends "paryatak/base.html"%}

{% block content %}

<article class="main">
<h1 class="page-heading"> Contact </h1>
<div id="form">
<form action="process.php">
<p>
<label for="name">Name:</label>
<input type="text" name="name" placeholder="Your Name" required>
</p>
<p>    
<label for="name">Email:</label>
<input type="text" name="email" placeholder="Your email" required>
</p>
<p>
<label for="name">Subject:</label>
<input type="text" name="subject" placeholder="Subject" required>
</p>
<p>    
<label for="name">Message:</label>
<textarea name="message" id="message" cols="30" rows="10" placeholder="Enter Message" required></textarea>
</p>
<p>
<input  id="submit" type="submit" name="submit" value="Send Message">
</p>
</form>
</div>
</article>
<footer>
	{% endblock content %}

paryatak/templates/paryatak/home.html
{% extends "paryatak/base.html"%}
{% load static %}
{% block content %}
<img class ="rounded-circle article-img"src="{{ post.author.profile.image.url }}">

<div class="content">
  <div class="container">
	<div id="home-video" style="">
		<!--<img src="images/we.jpeg" alt="Responsive Images">--><video id="video1" width="750px" height="400px" controls="controls">
		  <source src="{% static "b.mp4" %}" type="video/mp4">
		  	<source src="{% static "b.mp4" %} "type="video/ogg">
		</video>

		// <script>
		// var vid = document.getElementById("video1");

		// function myFunction() { 
		//   var text1 = vid.addTextTrack("caption");
		//   text1.addCue(new TextTrackCue("Test text", 01.000, 04.000, "", "", "", true));
		// } 
		// </script>
	</div>

</div>
<br />
  <div class="container bg-light">

<div class="  p-3 p-md-5 m-md-3 text-center bg-light link" style="height:300px; ">
  <div class="col-md-5  mx-auto " style="margin-top:0px">
    <h1 class="font-weight-normal">Visit Nepal!!!</h1>
  </div>
    <p class="lead font-weight-normal" style="color-blue;">Feel Free to express all your experience with us.</p>
    <a class="btn btn-outline-primary" href="#">Link to Testomonial</a>
  
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
</div>
</div>
<br />
</div>

  <div class="container" style="height:450px; width:950px;">
      <div class="space">
    <div class="header">
      <br />
        <h2> What's New<span>In Nepal</span> </h2>
</div>
    </div> 
<br />
<div class="d-md-flex flex-md-equal w-100 my-md-3 ">
       <div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="{% static "images/Dashain.jpg" %}" alt="Avatar" style="width:300px;height:300px;">
        <div class="card-img-overlay">
    <h1 class="card-title"style="color:grey;">Dashain</h1>
    </div>
    </div>
    <div class="flip-card-back">
      <h1>Dashain</h1>
          <p >Dashain is the main festival in Nepal. It is celebrated for long 10 days for worshipping Goddeess Durga.</p>
          <a class="btn btn-outline-primary" href="#">Explore More</a>
  



    </div>
  </div>
</div> 
       <div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="{% static "images/tihar.jpg" %}" alt="Avatar" style="width:300px;height:300px;">
        <div class="card-img-overlay">
    <h1 class="card-title" style="color:grey;">Tihar</h1>
    </div>
    </div>
    <div class="flip-card-back">
      <h1>Tihar</h1>
          <p >Tihar is also one of the main and most liked festivals in nepal. It is also called festivals of light.</p>
           <a class="btn btn-outline-primary" href="#">Explore More</a>

    </div>
  </div>
</div>
<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="{% static "images/losar1.jpg" %}" alt="Avatar" style="width:300px;height:300px;">
        <div class="card-img-overlay">
    <h1 class="card-title" style="color:grey;">Losar</h1>
    </div>
    </div>
    <div class="flip-card-back">
      <h1>Losar</h1>
          <p >Losar is a new year's festival, celebrated on the first day of the lunisolar Tibetan calendar by Buddhists.</p>
           <a class="btn btn-outline-primary" href="#">Explore More</a>

    </div>
  </div>
</div>  
</div>
</div>
<br />
<div class="container" style="width:950px">
<div class="ppp">

    <div class="space">
    <div class="header">
        <h2> Discover<span> Nepal</span> </h2>
</div>
    </div>
<div class="card-deck">
  <div class="card text-white bg-info mb-3" >
    <img src="{% static 'images/lumbini3.jpg'%}"class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Lumbini.</h5>
      <p class="card-text">Lumbini mainly is famous because it is a birthplace of Gautam Buddha.</p>
    <a href="/discover/4/" class="btn btn-light">View Details...</a>    
    </div>
  </div>
 <div class="card text-white bg-info mb-3" style="width: 18rem;">
    <img src="{% static 'images/solu2.jpg'%}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Solukhumbhu</h5>
      <p class="card-text"> Solukhumbu is know for its many beautiful huge Himalayas. Mount Everest, the highest peak of world is located here.</p>
        <a href="/discover/5/" class="btn btn-light">View Details...</a>
    </div>
  </div>
    <div class="card text-white bg-info mb-3" style="width: 18rem;">
    <img src="{% static 'images/h.jpg'%}" class="card-img-top" alt="...">
    <div class="card-body" style="height:250px">
      <h5 class="card-title">Mustang</h5>
      <p class="card-text">In the eighth century, during the Yarlung Dynasty, Buddhism reached Tibet. From Tibet, its cultures and religions are spread further to Mustang.</p>
        <div class="detail">
        <a href="/discover/7/" class="btn btn-light">View Details...</a>
            </div>
    </div>
  </div>

    </div>  
    </div>
           
    </div>
    
{% endblock content %}

    

paryatak/templates/paryatak/login.html
{% extends "paryatak/base.html"%}
{% load static %}
{% block content %}
<article class="main">
<div class="loginMain">
<div class="container">
<div class="loginForm">
<div>
<!--
<h2 style="padding:20px 20px 20px 20px;" class="display-7">
<span>Welcome</span>
</h2>
-->
<h1 style="margin:0 auto;" class="display-5">
<span>Sign In</span>
</h1>
</div>
<br>
<hr>
<br>

<form action="proces.php" method="post">
	{% csrf_token %}
<div class="form-group">
<input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Username or Email" required>

</div>

<div class="form-group">
    
<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
<small id="emailHelp" class="form-text text-muted"><a class="pas" href="#">Forgotten password?</a></small>
</div>

<div class="form-check mb-2">
<input class="formss" type="checkbox" id="autoSizingCheck">
<label class="keepme" for="autoSizingCheck">
<strong>Keep me logged in</strong>
</label>
</div>
<br>

<div class="down">
<button style="margin-left:0px;" type="submit" class="btn btn-info btn-lg">Sign In</button>
<br>
    <p class="lead"><strong>Don't have an account?</strong></p> 
    <a class="lead" href="register.html">Register</a>
    </div>
</form>

</div>
</div>
</div>



</article>
{% endblock content %}

paryatak/templates/paryatak/searchtickets.html
{% extends "paryatak/base.html"%}
{% load static %}
{% block content %}
<h1>{{user.username}} Tickets</h1>
{% for ticket in tickets %}
	<li><a href="{% url 'paryatak:samrat2' ticket.id %}" id = "sagar">{{ ticket.seat }}</a></li>
{% endfor %}


<script
			  src="https://code.jquery.com/jquery-3.4.1.js"
			  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
			  crossorigin="anonymous">
			  	
</script>
<script type="text/javascript">
	

		 $('#sagar').click(function(){
			alert('Success! Your seat has been cancled. Please check your email for more information');
				 		 
		});

	
</script>

{% endblock content %}